spring:
  application:
    name: employee-payroll-service

  threads:
    virtual:
      enabled: true

  logging:
    level:
      org.springframework: INFO
      org.hibernate.SQL: DEBUG
      org.springframework.boot.autoconfigure: DEBUG

  # Database connection - PostgresSQL
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: ${POOL_SIZE:10}

  # Database migration
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${IS_FLYWAY_BASELINE_ON_MIGRATE:true}
    validate-on-migrate: ${IS_FLYWAY_VALIDATE_ON_MIGRATE:true}
    locations: classpath:db/migration

server:
  port: 8080

